spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: java0101

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
